#@ load("@ytt:data", "data")

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: helm-writer
  namespace: tap-tasks
spec:
  description: |-
    A task that packages and publishes a helm chart.
  params:
    - name: source-url
      type: string
      description: 
    - name: image
      description: 
      type: string
  steps:
    - name: helm-package
      image: docker.io/lachlanevenson/k8s-helm@sha256:5c792f29950b388de24e7448d378881f68b3df73a7b30769a6aa861061fd08ae
      env:
        - name: "HOME"
          value: "/tekton/home/"
      script: |-
        #!/usr/bin/env bash
        
        set -o xtrace
        echo $(params.source-url)
        helm -h
    - name: helm-publish
      image: cxscssa.azurecr.io/tap-1-7-0/tap-packages@sha256:b31bb7c399a5bddd802f20891d4e2f493bb7183286cfb13feba8b5aaea33a3bd
      env:
        - name: "HOME"
          value: "/tekton/home/"
      script: |-
        #!/usr/bin/env bash
        
        set -o xtrace
        echo $(params.image)