#@ load("@ytt:data", "data")

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: helm-writer
  namespace: tap-tasks
spec:
  description: |-
    A task that packages and publishes a helm chart.
  params:
    - name: source-url
      type: string
      description: 
    - name: image
      description: 
      type: string
  steps:
    - name: helm-package
      image: cxscssa.azurecr.io/tap-1-7-0/tap-packages@sha256:b31bb7c399a5bddd802f20891d4e2f493bb7183286cfb13feba8b5aaea33a3bd
      env:
        - name: "HOME"
          value: "/tekton/home/"
      script: |-
        #!/usr/bin/env bash
        set -o errexit
        set -o xtrace
        echo $(params.source-url)
      
        cd `mktemp -d`
        HELM_INSTALL_DIR="."

        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh

        ./helm version

        wget -qO- $(params.source-url) | tar xvz -m
        cd helm
        ./helm package .

    - name: helm-publish
      image: cxscssa.azurecr.io/tap-1-7-0/tap-packages@sha256:b31bb7c399a5bddd802f20891d4e2f493bb7183286cfb13feba8b5aaea33a3bd
      env:
        - name: "HOME"
          value: "/tekton/home/"
      script: |-
        #!/usr/bin/env bash
        
        set -o xtrace
        echo $(params.image)